### ISSUE TITLE
Publish changes to MS Office Store

### ISSUE THREAD

**Issue by mattpen** [phetsims/phet-office-mix#2]
https://msdn.microsoft.com/library/ff075782-1303-4517-91cc-b3d730e9b9ae(Office.15).aspx

We should publish an update soon with the new look and latest sims.

**Comment by mattpen** [comment]
The format has been updated and the manifest has been revised to point to our server.  I sent the materials to our MS contact to review, and plan on submitting them when I hear back from him.

The app can be previewed (preferably in IE11) by going to https://labsjs.blob.core.windows.net/sdk/LabsJS-1.0.4/labshost.html?lab=https://phet.colorado.edu/office-mix/store.html?PostMessageLabHost

**Comment by mattpen** [comment]
Kurt reviewed the manifest and made some changes.  I will submit the manifest by Monday.  Kurt requested that we send him some feedback on the review and publication process when complete, how easy was it to complete/understand, how quickly did it go, etc.

**Comment by mattpen** [comment]
I submitted the new manifest to the Office Store, it is in Pending Approval status.  Kurt mentioned this step may take about a week on the MS side.

**Comment by mattpen** [comment]
The app passed the initial scan (for viruses and inappropriate content) and was updated with an estimated response date of 11/11/16 (today).

**Comment by mattpen** [comment]
Estimated response date was updated to today (11/14)

**Comment by mattpen** [comment]
Estimated response date has changed again to `...`

**Comment by mattpen** [comment]
The validation failed because the app does not load on a Mac.  I'll have to troubleshoot this problem and resubmit.

**Comment by mattpen** [comment]
I installed office on Bose today and the app loads as expected.  I'm following up with Kurt Berglund on the next steps.

**Comment by ariel-phet** [comment]
@mattpen why are you doing any of this on Bose? Why not on your main development machine since that has windows?

**Comment by mattpen** [comment]
@ariel-phet - The validation failed because the app is not working on Powerpoint for Mac.

**Comment by mattpen** [comment]
![image](https://cloud.githubusercontent.com/assets/11747676/20366909/759f4c5a-ac0a-11e6-845a-be3e04af5017.png)

**Comment by mattpen** [comment]
As far as I can tell, everything is working on Windows.

**Comment by ariel-phet** [comment]
@mattpen ah, I was misinterpreting the above, that makes sense now. That must be fairly new since in the past office mix was not available on powerpoint for the mac

**Comment by mattpen** [comment]
I think add-ins were added to PPT for Mac in Office 365.  I installed Office 2016 earlier today and the add-ins were not available there.

**Comment by mattpen** [comment]
I was able to get the app running in PPT for Mac.  The only problem I could find is that some apps would get stuck on the PhET splash screen and not load. Per Kurt's recommendation, I sent the following email last week.  I'm still waiting on a response.

> From: Matthew Pennington <Matthew.Pennington@colorado.edu>
> Date: Thu, Nov 17, 2016 at 2:02 PM
> Subject: Help with office-mix app on Powerpoint for Mac
> To: @microsoft.com
> Cc: @microsoft.com
>
>
> Hi Dan,
> 
> Kurt recommended that I contact you for help with our office-mix app.  It failed validation due to not working on a Mac. I've attached the validation report.  The only problem I've been able to find is that the some of the sims do not finish loading when launched in a Mac.  They all work as expected on Windows.  I've tested the sims in Safari using labsjs: https://labsjs.blob.core.windows.net/sdk/LabsJS-1.0.4/labshost.html?lab=https://phet.colorado.edu/office-mix/store.html?PostMessageLabHost, and they appear to be working as designed.  I'm trying to setup Vorlonjs to troubleshoot the sims in powerpoint itself.  I followed the instructions here: https://dev.office.com/docs/add-ins/testing/debug-office-add-ins-on-ipad-and-mac.  I have it running on http but it will not respond over ssl.
> 
> Could you please assist if possible? Thanks in advance.
> 
> -Matt Pennington
>>>

**Comment by mattpen** [comment]
Microsoft responded today.   It looks like the failure was a lack of support for webkit audio, but it will be fixed soon and they will not fail our app submission for that reason again, I'll resubmit today.

> From: Sudheer Maremanda
> Date: Mon, Nov 21, 2016 at 6:49 PM
> Subject: RE: Help with office-mix app on Powerpoint for Mac
> To: Dan Saunders, Matthew Pennington
> Cc: Kurt Berglund
>
>
> Hi Matt – 
> Thanks for contacting us. We found that API required to enable web audio was not implemented on Office for Mac – hence preventing your add-in from loading when it calls webkitAudioContext. We have since fixed this issue and will be shipping it later this month [thanks for bringing this to our attention!]. In the meantime, you are welcome to resubmit your app for validation after making changes required to load your add-in even if this API fails.
>  
> I’ll be happy to help you with Vorlon as well, but might be easier to get on a quick skype call to discuss it. Let me know if you’ll be available at 10a PST tomorrow?
>  
> Thanks,
> -Sudheer

**Comment by ariel-phet** [comment]
@mattpen thanks for keeping this effort moving!

**Comment by mattpen** [comment]
I just resubmitted the app, I'll keep this issue updated with the progress.

**Comment by mattpen** [comment]
Changes were published early this morning and are now live on the office store.
