### ISSUE TITLE
Office-mix app appears broken

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/phet-office-mix#5]
A user emailed phethelp that the office mix app appears to be broken. Amy and I reproduced on our machines (both Mac), but it sounds like @ariel-phet also reproduced on his Windows.

When I try to 'insert' the PhET add-in, I get a brief loading animation, but then nothing happens.

<img width="1792" alt="screen shot 2017-03-21 at 12 57 21 pm" src="https://cloud.githubusercontent.com/assets/5090275/24165427/f71ff12a-0e35-11e7-9cf2-96a9d417133c.png">

**Comment by mattpen** [comment]
@oliver-phet - I think it should be fixed now.  It looks like the script that automatically updates it has a bug.

**Comment by oliver-phet** [comment]
Maybe there is a delay for the fix to come through? I just tried again and am getting the same behavior.

**Comment by mattpen** [comment]
![image](https://cloud.githubusercontent.com/assets/11747676/24166642/8c0ee018-0e39-11e7-92aa-ab5b53871c4e.png)

Did you try pressing reload?  That fixed it for me.

**Comment by oliver-phet** [comment]
Yep, I reloaded, removed and re-added the add-in, and restarted PP.
<img width="1088" alt="screen shot 2017-03-21 at 1 25 47 pm" src="https://cloud.githubusercontent.com/assets/5090275/24166746/f0e1e8f0-0e39-11e7-91f4-d23216a73458.png">

After I click, Reload, I get a brief loading animation, then the screen remains blank.

**Comment by mattpen** [comment]
It may be subject to caching on the Microsoft side.  It is a static file and not cached in varnish, but the test environment is still showing errors too:  https://labsjs.blob.core.windows.net/sdk/LabsJS-1.0.4/labshost.html?lab=https://phet.colorado.edu/office-mix/store.html?PostMessageLabHost

If you add an arbitrary query parameter, it works normally: https://labsjs.blob.core.windows.net/sdk/LabsJS-1.0.4/labshost.html?lab=https://phet.colorado.edu/office-mix/store.html?PostMessageLabHost&1234

**Comment by mattpen** [comment]
@oliver-phet - Did you have a chance to check on the Mac again today?  The app is still working for me as of today in the labsjs links above and in Powerpoint for Windows.

**Comment by oliver-phet** [comment]
Working again on my Mac. I'll close for now.

**Comment by mattpen** [comment]
This is a new problem, the update script is working as expected.
