### ISSUE TITLE
Office-Mix app in OneNote

### ISSUE THREAD

**Issue by mattpen** [phetsims/phet-office-mix#7]
From Kurt Berglund:

> BTW - I believe OneNote now supports these office add-ins - and PhET in OneNote would be pretty awesome. And I think the current app might just work “for free” without any changes other than marking OneNote in the manifest.  So something to think about - I imagine OneNote people would be excited and I can see if I can find someone to help.  One of their big customers is Edu and they have this class notebook feature to let a teacher manage a classroom full of notebooks., which I think gets pretty big usage

@ariel-phet - does this sound worth pursuing, if so can you assign a priority?

**Comment by ariel-phet** [comment]
@mattpen it does seem worth pursuing, I am going to mark low priority for the moment. I would say we get it working after the Android app is all worked out.

**Comment by mattpen** [comment]
@ariel-phet - Would we still address this if the MS delivered Windows app is successful?

**Comment by ariel-phet** [comment]
Considering we have hear nothing more about this idea, and MS is redoing the whole office mix thing anyhow, I think this issue can be closed.
