### ISSUE TITLE
Does this repo need a license?

### ISSUE THREAD

**Issue by samreid** [phetsims/phet-office-mix#8]
Discovered in https://github.com/phetsims/tasks/issues/875

**Comment by samreid** [comment]
@zepumph and/or @mattpen can you please read through the notes in https://github.com/phetsims/tasks/issues/875 and make a recommendation for what license this repo should be?

**Comment by mattpen** [comment]
@samreid - Based on the decisions made in phetsims/tasks#875 I'd say the code we developed should be MIT. However, Microsoft developed a lot of this code for us and didn't indicate what the license should be for their code.  I'll reach out to our MS contact and ask them.

**Comment by mattpen** [comment]
@zepumph - I'll handle this one, removing your assignment.

**Comment by samreid** [comment]
@mattpen I sent you an email about licensing information that may or may not help.

**Comment by mattpen** [comment]
Kurt said that the MIT license should be fine.
